### ISSUE TITLE
Split install/any-kubernetes-cluster/ into multiple pages 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/ux#11]
## What is changing? (Please include as many details as possible.)
We ought to split the main "install doc" (page referenced in title) into sections which necessitate "progressing" along the install path. 

## How will this impact our users?
When users first click onto this page from https://knative.dev/docs/install/ they will no longer see a "wall of text" and instead be shown each of the components of the install separately. 

As far as users are concerned, this change will...
1.  will be a more digestible experience for users 
2. allows issues to be opened against portions of the installation docs instead of "the install doc" 
3. allow more information to be put in these sections without the page becoming unwieldy 

## Context
In order to understand where the road-blocks exist in our install process, we need more fine-grained data on where users are falling off the installation journey. 

This change also tees us up to make changes to the language in each section and be able to measure how those changes impact completion rates. 

## Prototype
Any time you see an arrow in this prototype, it means there is a separate page with "Next" and "Previous" linking them together in the direction of the arrows.

Final Prototype: 
![Install Split Prototyping Final](https://user-images.githubusercontent.com/16281246/112491999-3ec98f00-8d57-11eb-8751-412414afa11c.png)

**Comment by snneji** [comment]
Is this the same as #3018? The first part of that issue says we should split the topic into subsections. I feel like splitting the topic into subsections would also increase usability.

**Comment by omerbensaadon** [comment]
@snneji sorry for the confusion, going to split this story!

**Comment by omerbensaadon** [comment]
@snneji split!

**Comment by omerbensaadon** [comment]
https://github.com/knative/docs/issues/3361 and https://github.com/knative/docs/issues/3362 are child issues of this epic!

**Comment by omerbensaadon** [comment]
I... think this is done?

**Comment by omerbensaadon** [comment]
@snneji I know you said you were adding other issues

**Comment by snneji** [comment]
Yes, but they are not within the scope of this issue. I think we can close this too.
