### ISSUE TITLE
Sample App: UI website design

### ISSUE THREAD

**Issue by Leo6Leo** [knative/ux#113]
### Problem

Create the design file for the UX design picture in [the design doc](https://docs.google.com/document/d/1dYvNdHFf4qoiIbWWOWMLAXDAFpEjjRsa9lP27tpqPTI).

### [Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)
Which persona is this feature for?
Administrators and developers

### Exit Criteria
- A comprehensive design file, or an equivalent design document, detailing the user interface for the Sample App Bookstore homepage.

**Time Estimate** (optional):
How many developer-days do you think this may take to resolve? 
1-2

### Additional context (optional)
- This is a UI/UX design issue

**Comment by Mayaleeeee** [comment]
**# Bookstore Design Update**

Hello everyone,

I'm here to share my latest progress on the bookstore design project. 

You can view the homepage design in the attachment below or by accessing this [Figma](https://www.figma.com/file/JlNR7Fg58oIgZIqwc1OfXr) file.

Thank you



![IMG-20240229-WA0002.jpg](https://github.com/knative/ux/assets/105395613/187cc7d9-9663-472e-8d6b-60c0c534c211)

**Comment by Leo6Leo** [comment]
As we discussed on slack, can we have a light version as well? Just compare which one looks better

**Comment by Mayaleeeee** [comment]
> 
Yeah, thanks for the pinging.

The light mode for the bookstore can be seen below.
![Homepage_Light](https://github.com/knative/ux/assets/105395613/986a54e8-c65a-4695-9c27-b79f6ab8f11c)

**Comment by Leo6Leo** [comment]
From the discussion during today's UX WG meeting, here are the feedback:
- The comment boxes color in the light mode could be changed
- The space between the comment boxes can be increased to improve the readability 
Otherwise it looks great!

**Comment by Mayaleeeee** [comment]
> From the discussion during today's UX WG meeting, here are the feedback:
> - The comment boxes color in the light mode could be changed
> - The space between the comment boxes can be increased to improve the readability 
> Otherwise it looks great!

Thanks, @Leo6Leo 

All the feedbacks has been made.

**Comment by zainabhusain227** [comment]
I like the changes to the comment boxes! The new design looks good to me!

**Comment by Leo6Leo** [comment]
Approved. Closing this issue to indicate it as completed.
