### ISSUE TITLE
[bug] The Knative bi-weekly UX WG meeting reminder slack bot is sending reminders every week

### ISSUE THREAD

**Issue by Leo6Leo** [knative/ux#176]
As described in the title, the Knative bi-weekly UX WG meeting reminder slack bot is sending reminders every week.

The yaml file that is used to configure this github action is [here](https://github.com/knative/ux/blob/main/.github/workflows/bi-weekly-UX-WG-meeting-reminder.yaml) 

The reminder is sent to the CNCF slack #knative-ux channel. One example message is https://cloud-native.slack.com/archives/C05MW1AT1T8/p1722431220346959.

The next/most recent bi-weekly UX WG meeting will be happening August 8th, 2024.

Warn: In order to test the feature, the PR has to be merged for GitHub action to run.

/good-first-issue
/help-wanted
/kind bug

**Comment by Alokih** [comment]
Hey @Leo6Leo , Can I try this issue ?

**Comment by Leo6Leo** [comment]
Absolutely @Alokih , thanks for taking on this task.

/assign @Alokih

**Comment by Alokih** [comment]
Hey @Leo6Leo I have created a PR

**Comment by Leo6Leo** [comment]
@Alokih Thank you for your PR, I have left the comment on your PR, PTAL
