### ISSUE TITLE
Improve new user's understanding of Knative components and features

### ISSUE THREAD

**Issue by csantanapr** [knative/ux#2]
## How Might We...

 improve understanding of the many components and features of Knative? 

## For...

New Users

## So that...

Users who are new to Knative have a better understanding of each of the components of Knative Eventing so they can build cool things, grow as users or contributors, and expand the credibility and reach of Knative. 

## Rationale

This is one of the main findings from user research presented at the [Round 1 Research Shareout](https://docs.google.com/presentation/d/10bmQ_hqWI4Zus_VtfvH1PPdXmsNUMDC6XNyz7L25ndc/edit#slide=id.gbba6a35acf_0_0)

## Potential Metrics

- [ ] We are currently tracking the "Getting Started" experience with Knative Eventing via User Interviews, the average score (1-5, 5 being the best) is currently a 1.9 ((2+2+1+2+3+0+2.5+3)/8)
- [ ] The exit rate at different stages of the Install or Walkthrough 

## Main Potential Features List (Feature ideas that do not appear here are not tracked and, therefore, do not exist)

- [x] User testing of an Eventing Walkthrough in the form of a Google Doc [Currently lives here](https://docs.google.com/document/d/1V_6Cjqbt0khUhewXnT_3_Hc2L0RDFThy4lHo8z-sEQ8/edit#heading=h.x4udhbow907h) 
^^^ See #21 ^^^
- [x] Publishing of Eventing Walkthrough on the Knative.dev site to be added
- [x] Create a "Getting Started" tutorial of Serving which lives directly after install, give users the option to continue on this tutorial or continue onto the Eventing installation. 
- [x] Link to the tutorial for Knative serving wherever Knative serving may be installed on the site 
- [ ] Create Architecture Diagram for Knative Eventing Components sample implementation
- [ ] Add community-created Eventing sample apps to knative-awesome repo
- [ ] Create and maintain a list of Eventing Sources in the UX repo, ensure it is easily findable on the site
- [ ] Create a clear path for contributing an existing source to UX Repo
- [ ] Audit and improve visibility of the "Writing an Event Source" guide which walks through how to create a Knative Source
 ^^^ Work started by Ashleigh in https://github.com/knative/docs/issues/3364 ^^

**Comment by omerbensaadon** [comment]
>- [x] User testing of an Eventing Walkthrough in the form of a Google Doc [Currently lives here](https://docs.google.com/document/d/1V_6Cjqbt0khUhewXnT_3_Hc2L0RDFThy4lHo8z-sEQ8/edit#heading=h.x4udhbow907h) 
Created #21 as a child "Epic" to this

**Comment by omerbensaadon** [comment]
I think we can call this done for now
