### ISSUE TITLE
Painful to consume content from the website using Left and Right navigation bars

### ISSUE THREAD

**Issue by csantanapr** [knative/ux#23]
## Friction
I socialized the problem in [slack](https://knative.slack.com/archives/C01JBD1LSF3/p1615469550053700) you can see some comments in the thread.

I have problems searching, navigating, and reading the content on the website.
There are multiple problems with the left navigation.
- The font looks the same between section header and sub sections
- Font is to large and titles too long for the space in the nav that all titles wrap
- When title wrap it gets confuse as being a section on the next section
- No clear ordering of the sub sections
- When drilling into a section, the other sections making impossible to see the whole site index at once.
- Once in a page, there is no table of content floating on the right nav
-
![image](https://user-images.githubusercontent.com/1094878/111853875-12df8100-88f3-11eb-8e49-afc62f7da9c1.png)

## 🤕 1-10 Scale of Pain
Pain *8*

## (Optional) 🧙‍♀️ "Magic Wand" solution
I would like the problems addressed with the left Nav, here I gather possible solutions provided by other websites, I had a magic wand I would combine all these solutions into a single one that provides a delightful experience
![image](https://user-images.githubusercontent.com/1094878/111853937-47533d00-88f3-11eb-8510-efee3dc57ea7.png)
![image](https://user-images.githubusercontent.com/1094878/111853941-4cb08780-88f3-11eb-8153-a6e7debaee28.png)
![image](https://user-images.githubusercontent.com/1094878/111853959-6520a200-88f3-11eb-8e7f-3baadc034b82.png)
![image](https://user-images.githubusercontent.com/1094878/111853965-694cbf80-88f3-11eb-9b33-bf9cc3846dbf.png)

**Comment by omerbensaadon** [comment]
+1 

I think the most pressing issue for me is having a "collapsable" side-nav...

**Comment by omerbensaadon** [comment]
Closed via MkDocs migration
