### ISSUE TITLE
[PROPOSAL] Merge the Docs + UX WG under "DUX WG" 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/ux#32]
Proposal: https://docs.google.com/document/d/12BUIqfRuJ3DT20KqRAlJZ6q8J_vEmueL-L4eFwiDfgU/edit?usp=sharing

**Comment by evankanderson** [comment]
We're interested in this direction, and want to see a complete charter.

**Comment by markusthoemmes** [comment]
+1

**Comment by omerbensaadon** [comment]
See Charter: https://docs.google.com/document/d/1-opvSEzJMRbB6fybvjuCyhFBZvHwXnkbgyOIzjlmrpo/edit#heading=h.arsmtwd7qezi

**Comment by evankanderson** [comment]
@julz @dprotaso @markusthoemmes @rhuss

**Comment by julz** [comment]
+1 from me.

**Comment by dprotaso** [comment]
+1

**Comment by rhuss** [comment]
+1

I think we are complete now ;-) (sorry for the delay)

**Comment by omerbensaadon** [comment]
Proposal accepted

**Comment by evankanderson** [comment]
+1, left some comments, but LGTM
