### ISSUE TITLE
Is there any plan to implement knative i18n ?

### ISSUE THREAD

**Issue by abrennan89** [knative/ux#36]
@SataQiu commented on [Mon Apr 22 2019](https://github.com/knative/docs/issues/1222)

**Describe the change you'd like to see**
Is there any plan to implement knative i18n?
At present, our website `https://knative.dev` only supports English.
To facilitate internationalization, we should consider supporting more languages.
I am very interested in implementing knative Chinese localization.
If you have any plans, please let me know.
I'm happy to make an effort in this area!

**Additional context**

---

@samodell commented on [Mon Apr 22 2019](https://github.com/knative/docs/issues/1222#issuecomment-485483420)

Related to #716  

Hi @SataQiu , and thanks for your interest in translating Knative into Chinese! So far, we don't have a firm plan for how to kick off i18n for Knative. As the project is still in its pre-beta phase, there will continue to be a great deal of change between now and the 1.0 version. Once we reach the beta phase, and in theory some more stability in the project, that will likely be the time for us to seriously look into adding translated languages. Sorry I don't have any concrete information for you, but we will update these issues when we have more information.

---

@knative-housekeeping-robot commented on [Tue Dec 03 2019](https://github.com/knative/docs/issues/1222#issuecomment-561137187)

Issues go stale after 90 days of inactivity.
Mark the issue as fresh by adding the comment `/remove-lifecycle stale`.
Stale issues rot after an additional 30 days of inactivity and eventually close.
If this issue is safe to close now please do so by adding the comment `/close`.

Send feedback to [Knative Productivity Slack channel](https://knative.slack.com/messages/CCSNR4FCH) or file an issue in [knative/test-infra](https://github.com/knative/test-infra/issues/new).

/lifecycle stale

---

@knative-housekeeping-robot commented on [Thu Jan 02 2020](https://github.com/knative/docs/issues/1222#issuecomment-570407321)

Stale issues rot after 30 days of inactivity.
Mark the issue as fresh by adding the comment `/remove-lifecycle rotten`.
Rotten issues close after an additional 30 days of inactivity.
If this issue is safe to close now please do so by adding the comment `/close`.

Send feedback to [Knative Productivity Slack channel](https://knative.slack.com/messages/CCSNR4FCH) or file an issue in [knative/test-infra](https://github.com/knative/test-infra/issues/new).

/lifecycle rotten

---

@samodell commented on [Mon Jan 06 2020](https://github.com/knative/docs/issues/1222#issuecomment-571219044)

/remove-lifecycle rotten

---

@samodell commented on [Wed Jan 22 2020](https://github.com/knative/docs/issues/1222#issuecomment-577317622)

I'm going to close #716  as a duplicate of this, and we'll use this issue to track translation.

/cc @toshi0607 , who was interested in helping with translation into Japanese.

We are still not ready for translation (see initial response above), but the progress is getting closer to a stable phase. I'll update this issue when we're ready to start work on translation.

---

@toshi0607 commented on [Wed Jan 22 2020](https://github.com/knative/docs/issues/1222#issuecomment-577455931)

I'm looking forward to update! I'm willing to support it.

---

@abrennan89 commented on [Fri Mar 05 2021](https://github.com/knative/docs/issues/1222#issuecomment-791756176)

@omerbensaadon is this something the UX WG can look at?
I can't see this ever being implemented by the docs WG in the foreseeable future, we just don't have the resources to facilitate something like this which isn't a priority for us.

---

@omerbensaadon commented on [Tue Apr 27 2021](https://github.com/knative/docs/issues/1222#issuecomment-827675187)

@SataQiu would you be willing to be the primary maintainer for this? Around 7% of our website visitors are coming from China so this makes sense, it's just something that would require a ton of overhead to maintain.

**Comment by omerbensaadon** [comment]
Not anytime soon
