### ISSUE TITLE
Provide Katacoda as additional getting started experience

### ISSUE THREAD

**Issue by csantanapr** [knative/ux#55]
Today we have a getting started an experience that folks can run for both serving and eventing.
https://knative.dev/docs/getting-started/

They can be run using `kn quickstart [kind | minikube]` it would be good to have the same tutorials on Katacoda

Today we have katacoda files, but they are not updated to 1.0, they don't match to the getting started tutorials.
https://github.com/knative/docs/tree/main/tutorials/katacoda

[ ] Update Katacoda files in docs repo
[ ] Create Katacoda account for "Knative" instead of personal one https://www.katacoda.com/swapb/scenarios/knative-intro
[ ] Update getting started quickstart page to make people aware they can run it in browser
[ ] Blog about the new Katacoda quickstart tutorial

**Comment by jsanin** [comment]
I would be happy to work on this

**Comment by csantanapr** [comment]
AWESOME! @jsanin 👍 
Reach out to us if you have any questions or want to show something

**Comment by jsanin-vmw** [comment]
I could not use the quickstart plugin. It took too long to setup an environment and the katacoda environments have limited capacity which caused additional delays.

I have created a couple of PRs, one for [serving](https://github.com/knative/docs/pull/4893) and the other for [eventing](https://github.com/knative/docs/pull/4961). Both of them use a katacoda builtin environment kubernetes-cluster-running:1.18. Which led me to use an older knative version (v0.22.3/serving-crds.yaml - v0.22.3/serving-core.yaml)

Even though the previous limitations described, I was able to use most of text on https://knative.dev/docs/getting-started/first-service/ and https://knative.dev/docs/getting-started/first-autoscale/ in the serving katacoda tutorial. Both ended up being pretty similar.
Likewise for the eventing katacoda tutorial, I was able to use most of the text on https://knative.dev/docs/getting-started/getting-started-eventing/

**Comment by Cali0707** [comment]
Closing as not planned based off: https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/
